#define TWOCOMPONENT
#define DENSRATIO
#define SECOND_ORDER
#define DOBENCHMARK
#define DOXDMF
#define noWRITEPRESS

#define INTERFACE_INCOMP
#define noREPULSIVE_FLUX

#define noSMAGORINSKI

#define noINTERNAL_OBSTACLES

#define GPUTILEX 8
#define GPUTILEY 8
#define GPUTILEZ 8
